import {useEffect, useMemo, useState} from 'react';
import {fetchLocalizedResource} from '../api/pokeApi';
import {useLanguage} from '../context/LanguageContext';
import {localizedName} from '../utils/pokemonLocalization';

function MoveList({pokemon}) {
    const {language,t}=useLanguage();const ko=language==='ko';
    const versions=useMemo(()=>[...new Set(pokemon.moves.flatMap(m=>m.version_group_details.map(v=>v.version_group.name)))],[pokemon]);
    const [version,setVersion]=useState(versions.at(-1)||'');const [page,setPage]=useState(0);const [data,setData]=useState(null);const [error,setError]=useState(false);
    const filtered=useMemo(()=>pokemon.moves.filter(m=>m.version_group_details.some(v=>v.version_group.name===version)),[pokemon,version]);
    useEffect(()=>{let active=true;Promise.all(filtered.slice(page*10,page*10+10).map(async m=>({move:await fetchLocalizedResource('move',m.move.name),methods:m.version_group_details.filter(v=>v.version_group.name===version)}))).then(result=>{if(active)setData(result);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[filtered,page,version]);
    const methodName=name=>({ 'level-up':ko?'레벨업':'Level up',machine:ko?'기술머신':'Machine',egg:ko?'유전':'Egg',tutor:ko?'기술 가르침':'Tutor'}[name]||name);
    return <div className="game-data"><label>{ko?'게임 버전 그룹':'Game version group'}<select value={version} onChange={e=>{setVersion(e.target.value);setPage(0);setData(null);setError(false);}}>{versions.map(v=><option key={v} value={v}>{v.replaceAll('-',' ')}</option>)}</select></label><p className="content-note">{ko?'게임명은 API의 영문 식별명으로 표시합니다. 습득 방법은 선택한 게임 기준이며, 위력·명중·PP는 API의 현재 값으로 과거 게임과 다를 수 있습니다.':'Game groups use API English identifiers. Learning methods follow the selected game; power, accuracy, and PP use current API values and may differ in older games.'}</p>{error?<p role="status">{ko?'기술 정보를 불러오지 못했습니다.':'Unable to load moves.'}</p>:!data?<p role="status">{ko?'기술 불러오는 중…':'Loading moves…'}</p>:<div className="move-table-wrap"><table className="move-table"><thead><tr>{[ko?'기술':'Move',ko?'타입':'Type',ko?'분류':'Category',ko?'위력 / 명중 / PP':'Power / Accuracy / PP',ko?'배우는 방법':'Learn method'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.map(({move,methods})=><tr key={move.id}><td>{localizedName(move.names,language,move.name)}</td><td>{t(`type_${move.type.name}`)}</td><td>{{physical:ko?'물리':'Physical',special:ko?'특수':'Special',status:ko?'변화':'Status'}[move.damage_class.name]}</td><td>{move.power??'—'} / {move.accuracy??'—'} / {move.pp??'—'}</td><td>{methods.map((m,i)=><div key={i}>{methodName(m.move_learn_method.name)}{m.level_learned_at>0?` · Lv.${m.level_learned_at}`:''}</div>)}</td></tr>)}</tbody></table></div>}<div className="content-pagination"><button disabled={page===0} onClick={()=>{setPage(p=>p-1);setData(null);setError(false);}}>{ko?'이전':'Previous'}</button><span>{page+1} / {Math.max(1,Math.ceil(filtered.length/10))}</span><button disabled={(page+1)*10>=filtered.length} onClick={()=>{setPage(p=>p+1);setData(null);setError(false);}}>{ko?'다음':'Next'}</button></div></div>;
}
function EncounterList({pokemon}) {
    const {language}=useLanguage();const ko=language==='ko';const [data,setData]=useState(null);const [error,setError]=useState(false);const [version,setVersion]=useState('');
    useEffect(()=>{let active=true;fetchLocalizedResource('pokemon',`${pokemon.id}/encounters`).then(d=>{if(active){setData(d);setVersion(d[0]?.version_details[0]?.version.name||'');}}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[pokemon.id]);
    if(error)return <p role="status">{ko?'출현 정보를 불러오지 못했습니다.':'Unable to load encounters.'}</p>;
    if(!data)return <p role="status">{ko?'출현 정보 불러오는 중…':'Loading encounters…'}</p>;
    if(!data.length)return <p>{ko?'API에 등록된 야생 출현 정보가 없습니다. 게임에서 획득할 수 없다는 뜻은 아닙니다.':'No wild encounters are recorded by the API. This does not mean the Pokémon cannot be obtained in a game.'}</p>;
    const versions=[...new Set(data.flatMap(x=>x.version_details.map(v=>v.version.name)))];
    return <div className="game-data"><label>{ko?'게임 선택':'Select game'}<select value={version} onChange={e=>setVersion(e.target.value)}>{versions.map(v=><option key={v} value={v}>{v.replaceAll('-',' ')}</option>)}</select></label><p className="content-note">{ko?'장소·출현 방법은 API 원문입니다. 자료가 없는 게임과 지역은 표시되지 않습니다.':'Locations and encounter methods use API identifiers. Games and areas without data are omitted.'}</p><ul className="encounter-list">{data.filter(x=>x.version_details.some(v=>v.version.name===version)).map(x=>{const d=x.version_details.find(v=>v.version.name===version);return <li key={x.location_area.name}><strong>{x.location_area.name.replaceAll('-',' ')}</strong><span>{[...new Set(d.encounter_details.map(e=>`${e.method.name.replaceAll('-',' ')} · Lv.${e.min_level}–${e.max_level}`))].join(' / ')}</span></li>;})}</ul><p className="content-note">{ko?'날씨·시간·진행 상태 등의 추가 출현 조건은 게임 내에서 확인하세요.':'Check the game for additional weather, time, or progression requirements.'}</p></div>;
}
export default function PokemonGameData({pokemon}) {
    const {language}=useLanguage();const ko=language==='ko';const [moves,setMoves]=useState(false);const [encounters,setEncounters]=useState(false);
    return <section className="content-section"><div className="content-heading"><span>GAME NOTEBOOK</span><h2>{ko?'게임에서 만나고 키우기':'Find and train it in a game'}</h2></div><details onToggle={e=>setMoves(e.currentTarget.open)}><summary>{ko?'게임별 배우는 기술':'Moves by game'}</summary>{moves&&<MoveList pokemon={pokemon}/>}</details><details onToggle={e=>setEncounters(e.currentTarget.open)}><summary>{ko?'게임별 야생 출현 장소':'Wild encounters by game'}</summary>{encounters&&<EncounterList pokemon={pokemon}/>}</details></section>;
}
